version: '3.7'

services:
  flask-app:
    mem_limit: 256m  # Retain memory limit
    build:
      context: .
      dockerfile: Dockerfile.test  # Use a specific Dockerfile for testing
    environment:
      - FLASK_ENV=testing
      - FLASK_APP=app.py
      - TESTING=True
    command: ["pytest", "tests/"]
    volumes:
      - .:/app

  nginx-app:
    image: nginx
    ports:
      - 5555:5001  # Keep port forwarding for the testing environment
    depends_on:
      - flask-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
